services:
  # --- 1. データベース (PostgreSQL) ---
  db:
    image: postgres:15
    ports: ["5433:5432"]
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./database:/var/lib/postgresql/data # Synchronize the host's ./database directory with /var/lib/postgresql/data inside the container
    restart: always

  # --- 2. 行列管理 (Redis) ---
  redis:
    image: redis:alpine
    restart: always

  # --- 3. バックエンド (FastAPI) ---
  backend:
    build:
      context: .
      dockerfile: dockerfiles/dockerfile_backend.prod
    ports: ["8081:8080"]
    volumes:
      - ./static_data:/app/static_data
      - ./backend/uploads:/app/uploads
    depends_on:
      - db
      - redis
    env_file: [.env]
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080
    environment:
      - PYTHONPATH=/app
    restart: always
    deploy:
      resources:
        reservations:
          cpus: "4.0"
          memory: 1G

  # --- 4. ジャッジワーカ (Celery) ---
  worker:
    image: my_judge_worker_image
    build:
      context: .
      dockerfile: dockerfiles/dockerfile_backend.prod
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backend/uploads:/app/uploads
      - ./backend/makefiles:/app/makefiles
    depends_on:
      - db
      - redis
    env_file: [.env]
    environment:
      - HOST_PROJECT_DIR=${PWD}
    command: celery -A app.asyncs.worker.celery_app worker --loglevel=info --concurrency=4
    restart: always
    deploy:
      resources:
        limits:
          cpus: "8.0" 

  # --- 5. フロントエンド (Nginx) ---
  frontend:
    build:
      context: .
      dockerfile: dockerfiles/dockerfile_frontend.prod
    ports: ["3000:80"]
    restart: always

  # --- 6. Slack定期通知用スケジューラー ---
  slack-scheduler:
    build:
      context: .
      dockerfile: dockerfiles/dockerfile_backend.prod
    depends_on:
      - db
    env_file: [.env]
    command: python -m app.notification.slack
    restart: always

volumes:
  postgres_data:
