FROM python:3.9-slim

WORKDIR /app

# Install necessary system packages
RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    make \
    valgrind \
    docker.io \
    && rm -rf /var/lib/apt/lists/*

# Copy and install Python dependencies
COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install watchdog